apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: my/cool_project
deploy:
  kubectl:
    manifests:
    - k8s.yaml
ingress:
  - serviceName: my-service   # name of a Kubernetes Service resource want to connect to the public endpoint
    port: 9312
